name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
inouts:
  bucket:
    description: 'The S3 bucket name.'
    required: true
  bucket-region:
    decription: 'The region of the S3 bucket'
    required: false
    default: 'eu-central-1'
  dist-folder:
    description: 'The folder contained the deployable files.'
    required: true
outputs:
  website-url:
    description: 'The URL generated after website uploading'
runs:
  using: 'node16'
  main: 'main.js'
  
